[project]
name = "crewai-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "crewai[tools]>=0.186.1",
    "notebook>=7.4.5",
]
