research_task:
  description: >
    Find 3-5 interesting and recent facts about {Topic} as of 2025
  expected_output: >
    A bullet of 3-5 facts

writer_task:
  description: >
    Write a 100-words blog summary about {Topic} using the facts from the research
  expected_output: >
    A blog post summary